### PR TITLE
feat(config): add support for custom CA certificate when calling Key Vault

### PR DESCRIPTION
**Pull request by ttyS0e**
My clients want to use this plugin behind a corporate traffic inspection service, however NodeJS/Electron doesn't seem to respect the OS native truststore.

They get the console error:

`Self-signed certificate in chain`

This allows them to set a custom CA cert path for handshaking with the Vault endpoint.

See screenshot for config example:
image

### CODE REVIEW

**Comment by glconti** [comment]
Hi @ttyS0e thank you for you PR and sorry for my very late answer, the reason being loosing interest in Insomnia after they limited the feature set to not paying/not authenticated users.

I will merge you PR and publish a new version to npm.

**Comment by ttyS0e** [comment]
Thanks @glconti this is banging, client will be way happier loading from plugin hub instead of their fork.

**Comment by ttyS0e** [comment]
I looked into https://github.com/glconti/insomnia-plugin-azure-keyvault-secrets/pull/4 after I programmed all this haha!

It is a good idea, and I did wonder if there was some way to for example "prefer" env variable over the Insomnia config.

I just find that the users understand more when you can explicitly set the properties directly in the UI, and that would be clearer, same as you said.

**Comment by glconti** [comment]
> It is a good idea, and I did wonder if there was some way to for example "prefer" env variable over the Insomnia config.

I would use the plugin [insomnia-plugin-dotenv](https://insomnia.rest/plugins/insomnia-plugin-dotenv), it reads values from a chosen .env file and populates Insomnia env variables.

You could combine it with this plugin like this:

image

image

cc @oahmed-OS

**Pull request merged**
